package com.websocket.chat.providers;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Map;

@SpringBootTest
class JsonWebTokenProviderTest {

    @Autowired
    private TokenProvider tokenProvider;

    @Test
    void test(){
        Map<String, String> decoded = tokenProvider.decode("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJTSzFxc0xlWnJvVXQ3SG5nYUN1VSJ9.eyJnaXZlbl9uYW1lIjoiUm9zZW1iZXJnIiwiZmFtaWx5X25hbWUiOiJMaW1hIiwibmlja25hbWUiOiJyb3NlbWJlcmcuYmV6ZXJyYSIsIm5hbWUiOiJSb3NlbWJlcmcgTGltYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BRWRGVHA3OHhhSjlDUW9GRnR2anJqelR1SlJhMndMa1lqYm1DLUVjT2s2c0VRPXM5Ni1jIiwibG9jYWxlIjoicHQtQlIiLCJ1cGRhdGVkX2F0IjoiMjAyMy0wMi0wMVQxMToyOToxNS4zMzlaIiwiZW1haWwiOiJyb3NlbWJlcmcuYmV6ZXJyYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9kZXYtZTZtNmNuZTJybzB3d2NvYi51cy5hdXRoMC5jb20vIiwiYXVkIjoiamxBa3BhZEYzNmtkVDFyN0IyQndETlVOQmdwNVc5M2EiLCJpYXQiOjE2NzUyNTA5NTksImV4cCI6MTY3NTI4Njk1OSwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTM2MDkyNDM4MzI3NjY3ODY4MDEiLCJzaWQiOiJTRTVOZEpEMHdEMU9xTzJHcDdTVXR6WXVMVEQxaXR2dCIsIm5vbmNlIjoiZDNSU2FFVnFhRUZ3VmtScGVWOTFZVUl4Vm5GbWJUVkNTR2RpTUdobVYzWkVkMlZ5WDFkK2FHZEJZdz09In0.sHnv60cY0WawVuDUE8zGN54O79kHEV3HzWBhguecC2CKIwF1-XfWii_8a7aV6qYnd-HWFxcqQ5CngQQ7roCIHwWSonSR-1f4BKZ2Yx6ewPCU7NZf3fqTXpe2vjKym7UGHV4JaMPbku2qVmQVwR3RW0nuAG_fj9T4pewZAwK9hxsHMcSw8rgRyXwVzpAYFz2KzbS45-TmVGogG2pMgsNfg1NI2IoDpf2pbMesV1ebsR7OS-KsucV62Pru4veOwbum7_kOcWFcHXNSMaRAxmTcH7SzFH2y-EnU3J7WLkYaaPJWY-nbUjhGCfuEUPYzG_ZwN515iiCvoaB2RgYjIljIfg");
        System.out.println(decoded);
    }

}